### ISSUE TITLE
`onExit` event not emitted after successful connnection 

### ISSUE THREAD

**Issue by wzslr321** [plaid/plaid-link-ios#50] opened 2024-11-20 12:29 UTC
### Exit event not emitted after successful connection
---

I am using [plaid_flutter](https://github.com/jorgefspereira/plaid_flutter) that integrates with native SDKs to support plaid. I encountered an issue with `onExit` event not being emitted after successful connection on `iOS`.

### A detailed description of the steps to reproduce the issue

Due to the fact I am using it with Fluter, I am not aware of specific iOS api methods names. Therefore I include only high-level flow description. 

* Trigger plaid open
* Connect bank account
* Click `Finish` button after success

> Logs flow: 
```
flutter: Received LinkEvent from PlaidLink.onEvent stream, with name: TRANSITION_VIEW
flutter: Received LinkEvent from PlaidLink.onEvent stream, with name: OPEN
flutter: Received LinkEvent from PlaidLink.onEvent stream, with name: TRANSITION_VIEW
flutter: Received LinkEvent from PlaidLink.onEvent stream, with name: SELECT_INSTITUTION
flutter: Received LinkEvent from PlaidLink.onEvent stream, with name: TRANSITION_VIEW
flutter: Received LinkEvent from PlaidLink.onEvent stream, with name: OPEN_OAUTH
flutter: Received LinkEvent from PlaidLink.onEvent stream, with name: HANDOFF
```

I reported the issue in the `plaid_flutter` repository as well, here -> https://github.com/jorgefspereira/plaid_flutter/issues/141

### What you expected to see?

I expected plaid view to be fully dismissed, with a possibility to interact with the appliation again. 

### What you saw instead?

The plaid overlay was dismissed, but its native view was not (?) which led to greyed out application, that is impossible to interact with. To start using the app again, I must kill it and open it again.

<details><summary>Screenshots that show the state of the UI (if applicable)</summary>

</details>

---

When submitting an issue for Link on the web or within a Webview, please include the following information:

|       Name       | Value |
|------------------|-------|
| Link `env`       |    Sandbox  |
| Browser          |       |
| Operating system |   iOS 18.1  |

---

When submitting an issue for [**Plaid Link iOS**](https://github.com/plaid/link/tree/master/ios) please include the following information:

| Name            | Value |
|-----------------|-------|
| Link `env`      |   Not sure    |
| LinkKit version |    Not sure   |
| iOS version     |    18.1   |
| iOS device      |   iPhone 12    |

#### List of used 3rd party libraries (e.g. CocoaPods):

[Podspec from `plaid_link` repository
](https://github.com/jorgefspereira/plaid_flutter/blob/master/ios/plaid_flutter.podspec)
```
Pod::Spec.new do |s|
  s.name             = 'plaid_flutter'
  s.version          = '0.0.1'
  s.summary          = 'Plaid Link plugin for Flutter'
  s.description      = <<-DESC
Enables Plaid in Flutter apps.
                       DESC
  s.homepage         = 'http://github.com/jorgefspereira'
  s.license          = { :file => '../LICENSE' }
  s.author           = { 'Jorge Pereira' => 'jorgefspereira@icloud.com' }
  s.source           = { :path => '.' }
  s.source_files = 'Classes/**/*'
  s.public_header_files = 'Classes/**/*.h'
  s.dependency 'Flutter'
  s.dependency 'Plaid', '5.6.1'
  s.static_framework = true
  s.ios.deployment_target = '14.0'
end
```

* [Plaid](https://cocoapods.org/pods/Plaid)

**Comment by dtroupe-plaid** [comment] 2024-11-22 21:34
Hi @wzslr321,

>I encountered an issue with onExit event not being emitted after successful connection on iOS.

[OnExit](https://plaid.com/docs/link/ios/#onexit) is not emitted for a success connection. 

>This optional closure is called when a user exits Link without successfully linking an Item, or when an error occurs during Link initialization.

[OnSuccess](https://plaid.com/docs/link/ios/#onsuccess) should be emitted.

>The closure is called when a user successfully links an Item.

You also stated:

>I expected plaid view to be fully dismissed, with a possibility to interact with the appliation again. The plaid overlay was dismissed, but its native view was not (?) which led to greyed out application, that is impossible to interact with. To start using the app again, I must kill it and open it again.

You would need to provide code to reproduce this issue. Especially because you can be using a custom dismiss callback. I think it's best to report this in the Flutter SDK because presentation is handled there.

I am going to close this issue, but feel free to reply if I missed something or you need further clarification.

**Closed by dtroupe-plaid** 2024-11-22 21:34 UTC
