### ISSUE TITLE
SPM Package Takes a Huge Amount of Time to Resolve

### ISSUE THREAD

**Issue by waitbutY** [plaid/plaid-link-ios#43] opened 2024-06-27 18:37 UTC
*Plaid is our longest time to resolve out of 40+ packages*
---
Plaid can take 15-30 minutes to resolve the package in Swift Package Manager depending on internet connection.

Other SDKs have offered SPM specific repositories to solve this issue:
- Lottie: https://github.com/airbnb/lottie-spm
- Radar: https://github.com/radarlabs/radar-sdk-ios-spm

Can plaid also provide an SPM specific repository?

| Name            | Value |
|-----------------|-------|
| LinkKit version |   4.1.0    |
| Xcode version     |   15.4    |
| MacOS version | 14.5 |

**Comment by dtroupe-plaid** [comment] 2024-06-28 16:35
Duplicate of [36](https://github.com/plaid/plaid-link-ios/issues/36)

**Closed** 2024-06-28 16:35 UTC
