### ISSUE TITLE
Capture quick modal dismissal in `onExit` or `onEvent` callback 

### ISSUE THREAD

**Issue by ahmednour2021** [plaid/plaid-link-ios#31] opened 2024-01-12 19:17 UTC
*Please do not include your API `secret` or `public_key` in any issue.*
---
### A detailed description of the steps to reproduce the issue
Currently, in our iOS app, based on `onExit` callback we inform the user that he has exited the flow but when he dismisses it very quickly callback is not triggered 
* present plaid modal 
* quickly dismiss plaid view 
* check if `onExit` callback is triggered 

### What you expected to see?
onExit has been triggered  
### What you saw instead?
onExit not triggered neither onEvent
<details><summary>Screenshots that show the state of the UI (if applicable)</summary>

</details>

---

When submitting an issue for Link on the web or within a Webview, please include the following information:

|       Name       | Value |
|------------------|-------|
| Link `env`       |       |
| Browser          |       |
| Operating system |       |

---

When submitting an issue for [**Plaid Link iOS**](https://github.com/plaid/link/tree/master/ios) please include the following information:

| Name            | Value |
|-----------------|-------|
| Link `env`      |   dev    |
| LinkKit version |    5.0.1   |
| iOS version     |    17.0.1   |
| iOS device      |     iPhone 15 pro  |

#### List of used 3rd party libraries (e.g. CocoaPods):

* [Plaid](https://cocoapods.org/pods/Plaid)
*
*

**Comment by dtroupe-plaid** [comment] 2024-01-18 18:25
@ahmednour2021 can you confirm this is a separate issue from #33 ? The swipe down to dismiss gesture is disabled so I am not sure what you mean when you say.

>dismisses it very quickly callback is not triggered. 

Can you provide some more details and perhaps a video of this behavior?

**Comment by ahmednour2021** [comment] 2024-01-18 18:33
> @ahmednour2021 can you confirm this is a separate issue from #33 ? The swipe down to dismiss gesture is disabled so I am not sure what you mean when you say.
> 
> > dismisses it very quickly.
> 
> Can you provide some more details and perhaps a video of this behavior? Can you also let me know if you're using the default presentation or a custom presentation? If custom can you provide the relevant code?

@dtroupe-plaid 
Indeed it's a separate issue will try to provide a video of that soon

**Comment by dtroupe-plaid** [comment] 2024-02-05 17:04
@ahmednour2021 I am going to close this issue since there isn't enough information to reproduce the issue. If additional information is provided I can reopen the issue.

**Closed by dtroupe-plaid** 2024-02-05 17:04 UTC
